#  Copyright (c) 2012-2023, Jungschar EMK. This file is part of
#  hitobito_jemk and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_jemk.


# Settings relevant for the hitobito_jemk wagon
# Overrides settings from the main application
application:
  logo:
    height: 80
    width: 230
    background_color: "#ffffff"
  footer:
    logo_image: logo_ball.png
    logo_url: https://jemk.ch
  languages:
    de: Deutsch

  # non UI languages for assigning to person#language
  # additional_languages:
  #   en: Englisch

# The person with this email has root access to everything
# This person should only be used by the operators of the application,
# not the customers.
# Initially, a password reset token may be mailed from the application
# to this address to set a password.
root_email: hitobito-jemk@puzzle.ch
